# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8a5374eca1ffd90f483fae479cf5dcf75daed34c7855cdbfaa73ba0f8fec33771e97a483b6a3c170be486fdf72713cc740fa566e48274d77bab065e48eeca1f

test:
  secret_key_base: f5ac60bd185f55cf977a3706865b35b3e4140ba883562c0939f8495e0b6590923aca520979a4b6d689d628a27d287103fa4effc0a9388f490e2eb2f1d7d2073f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
